<template>
  <div class="page-container"><div class="page-head"><div><h2 class="page-title">司南推广链</h2><p class="page-subtitle">实时读取司南平台数据</p></div><el-button @click="load">刷新</el-button></div>
    <el-card shadow="never"><el-table :data="items" v-loading="loading" border>
      <el-table-column prop="promotion_name" label="推广链名称" min-width="170"><template #default="{row}"><div>{{row.promotion_name}}</div><CopyText :value="row.promotion_id"/></template></el-table-column><el-table-column prop="app_name" label="推广应用"/><el-table-column prop="content_type_name" label="内容体裁"/><el-table-column prop="client_os_name" label="系统"/><el-table-column prop="media_channel_name" label="媒体渠道"/><el-table-column label="推广内容" min-width="180"><template #default="{row}"><div>{{row.drama_title}}</div><CopyText :value="row.drama_id"/></template></el-table-column><el-table-column label="跳转节点" min-width="180"><template #default="{row}"><div>{{row.chapter_title}}</div><CopyText :value="row.chapter_id"/></template></el-table-column><el-table-column prop="landing_type_name" label="跳转方式"/><el-table-column prop="recharge_tpl_name" label="充值模板"/><el-table-column prop="pixel_name" label="像素名称"/><el-table-column prop="ad_convt_config_name" label="回传规则"/><el-table-column label="推广链接" min-width="120"><template #default="{row}"><el-button link type="primary" @click="showLink(row)">查看链接</el-button></template></el-table-column><el-table-column label="操作" fixed="right" width="130"><template #default="{row}"><el-button link @click="showLink(row)">链接</el-button><el-button link @click="goPublish(row)">去投放</el-button></template></el-table-column>
    </el-table><el-pagination class="pagination" v-model:current-page="page" v-model:page-size="pageSize" :page-sizes="[10,20,50,100]" layout="total, sizes, prev, pager, next, jumper" :total="total" @current-change="load" @size-change="changeSize"/></el-card>
    <el-dialog v-model="detailVisible" title="推广链" width="620px"><div v-if="detail" class="detail"><div class="row"><b>广告系列/组名称</b><span>{{detail.ad_group || detail.campaign_name || '-'}}</span><CopyText :value="detail.ad_group || detail.campaign_name"/></div><div class="row"><b>推广链接</b><span class="url">{{detail.landing_url || '-'}}</span><CopyText :value="detail.landing_url"/></div></div><el-empty v-else description="加载中"/></el-dialog>
  </div>
</template>
<script setup lang="ts">
import {ref,onMounted} from 'vue';import {ElMessage} from 'element-plus';import {CopyDocument} from '@element-plus/icons-vue';import {useRouter} from 'vue-router';import {sinanPromotionsApi} from '@/api/sinanPromotions'
const router=useRouter(),items=ref<any[]>([]),total=ref(0),page=ref(1),pageSize=ref(20),loading=ref(false),detailVisible=ref(false),detail=ref<any>();
const CopyText=(props:{value?:string})=>props.value?{template:`<el-button link type="primary" title="复制" onclick="navigator.clipboard.writeText('${String(props.value).replaceAll("'","\\'")}')"><el-icon><CopyDocument/></el-icon></el-button>`}:null;
async function load(){loading.value=true;try{const r=(await sinanPromotionsApi.list(page.value,pageSize.value)).data;items.value=r.Promotions||r.items||[];total.value=Number(r.total||r.Total||0)}finally{loading.value=false}}function changeSize(){page.value=1;load()}async function showLink(row:any){detailVisible.value=true;detail.value=(await sinanPromotionsApi.detail(row.promotion_id)).data}function goPublish(row:any){router.push({path:'/dashboard/batch-publish',query:{sinan_promotion_id:row.promotion_id}})}onMounted(load)
</script>
<style scoped>.pagination{justify-content:flex-end;margin-top:16px}.detail{border:1px solid #e5e7eb}.row{display:flex;align-items:center;min-height:58px;border-bottom:1px solid #e5e7eb;padding:0 14px;gap:12px}.row:last-child{border-bottom:0}.row b{width:120px;background:#f5f7fa;margin:-0px 0 -0px -14px;padding:20px 12px;color:#606266}.row span{flex:1;word-break:break-all}.url{line-height:24px}</style>
