<template>
  <div class="page-container">
    <div class="page-head"><div><h2 class="page-title">司南推广链</h2><p class="page-subtitle">数据实时来自司南，创建后可直接带入 Meta 批量投放。</p></div><div><el-button @click="load">刷新</el-button><el-button type="primary" @click="openCreate">新增推广链</el-button></div></div>
    <el-card shadow="never"><el-table :data="items" v-loading="loading"><el-table-column prop="promotion_name" label="推广链名称"/><el-table-column prop="drama_title" label="推广内容"/><el-table-column prop="chapter_title" label="跳转节点"/><el-table-column prop="ad_group" label="广告组"/><el-table-column label="推广链接" show-overflow-tooltip><template #default="{row}"><span v-if="row.landing_url">{{ row.landing_url }}</span><el-button v-else link type="primary" @click="showLink(row)">查看链接</el-button></template></el-table-column><el-table-column label="操作"><template #default="{row}"><el-button link type="primary" @click="showLink(row)">链接</el-button><el-button link @click="goPublish(row)">去投放</el-button></template></el-table-column></el-table></el-card>
    <el-dialog v-model="detailVisible" title="推广链" width="560px" class="sinan-link-dialog"><div v-if="detail" class="sinan-link-content"><div class="sinan-link-row"><div class="sinan-link-label">广告系列/组名称</div><div class="sinan-link-value"><span>{{ detail.ad_group || detail.campaign_name || '-' }}</span><el-button v-if="detail.ad_group || detail.campaign_name" link type="primary" class="copy-icon" title="复制" @click="copy(detail.ad_group || detail.campaign_name)"><el-icon><CopyDocument /></el-icon></el-button></div></div><div class="sinan-link-row link-value-row"><div class="sinan-link-label">推广链接</div><div class="sinan-link-value"><span>{{ detail.landing_url || '-' }}</span><el-button v-if="detail.landing_url" link type="primary" class="copy-icon" title="复制" @click="copy(detail.landing_url)"><el-icon><CopyDocument /></el-icon></el-button></div></div></div><el-empty v-else description="暂无数据"/></el-dialog>
    <el-dialog v-model="visible" title="新增推广链" width="720px"><el-form :model="form" label-width="110px"><el-form-item label="推广应用" required><el-select v-model="form.real_app_id" filterable style="width:100%"><el-option v-for="a in apps" :key="a.id" :label="a.name" :value="a.id"/></el-select></el-form-item><el-form-item label="链接名称" required><el-input v-model="form.promotion_name"/></el-form-item><el-form-item label="媒体渠道"><el-select v-model="form.media_channel"><el-option label="Meta" :value="1"/><el-option label="TikTok" :value="2"/></el-select></el-form-item><el-form-item label="内容体裁"><el-radio-group v-model="contentType"><el-radio-button label="SHORT_VIDEO">短剧</el-radio-button><el-radio-button label="COMIC">漫剧</el-radio-button></el-radio-group></el-form-item><el-form-item label="推广内容" required><el-select v-model="form.drama_id" filterable remote :remote-method="searchContent" :loading="contentLoading" style="width:100%" @change="loadChapters"><el-option v-for="d in dramas" :key="d.drama_id" :label="`${d.title || d.drama_title}（${d.drama_id}）`" :value="d.drama_id"/></el-select></el-form-item><el-form-item label="跳转节点" required><el-select v-model="form.chapter_id" style="width:100%"><el-option v-for="c in chapters" :key="c.chapter_id || c.id" :label="c.chapter_title || c.title || `第${c.sort_no}集`" :value="c.chapter_id || c.id"/></el-select></el-form-item><el-form-item label="系统"><el-select v-model="form.client_os"><el-option label="全部" :value="0"/><el-option label="Android" :value="1"/><el-option label="iOS" :value="2"/></el-select></el-form-item><el-form-item label="投放目标"><el-select v-model="form.delivery_goal"><el-option label="购物" :value="1"/></el-select></el-form-item><el-form-item label="跳转方式"><el-select v-model="form.landing_type"><el-option label="W2A" :value="1"/><el-option label="落地页" :value="2"/></el-select></el-form-item><el-form-item label="回传规则"><el-select v-model="form.ad_convt_config_id" clearable style="width:100%"><el-option v-for="r in rules" :key="r.id || r.ad_convt_config_id" :label="r.name || r.config_name" :value="r.id || r.ad_convt_config_id"/></el-select></el-form-item><el-form-item label="充值档位"><el-select v-model="form.recharge_tpl_id" clearable style="width:100%"><el-option v-for="r in recharge" :key="r.id || r.recharge_tpl_id" :label="r.name || r.template_name" :value="r.id || r.recharge_tpl_id"/></el-select></el-form-item><el-form-item label="Pixel"><el-select v-model="form.pixel_id" clearable style="width:100%"><el-option v-for="p in pixels" :key="p.id || p.pixel_id" :label="p.name || p.pixel_name" :value="p.id || p.pixel_id"/></el-select></el-form-item><el-form-item label="价格设置"><el-radio-group v-model="form.price_strategy_source"><el-radio :value="1">默认设置</el-radio><el-radio :value="2">自定义设置</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">创建推广链</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { CopyDocument } from '@element-plus/icons-vue'
import { useRouter } from 'vue-router'
import { sinanPromotionsApi } from '@/api/sinanPromotions'
const router = useRouter(), items = ref<any[]>([]), loading = ref(false), visible = ref(false), detailVisible = ref(false), detail = ref<any>(), saving = ref(false), contentLoading = ref(false), apps = ref<any[]>([]), dramas = ref<any[]>([]), chapters = ref<any[]>([]), rules = ref<any[]>([]), recharge = ref<any[]>([]), pixels = ref<any[]>([]), contentType = ref('SHORT_VIDEO')
const form = reactive<any>({ promotion_name: '', real_app_id: '', drama_id: '', chapter_id: '', media_channel: 1, landing_type: 1, pixel_id: '', ad_convt_config_id: '', recharge_tpl_id: '', price_strategy_source: 1, client_os: 0, turn_tag: 1, delivery_goal: 1, genre: 4 })
async function load() { loading.value = true; try { const d = (await sinanPromotionsApi.list()).data; items.value = d.Promotions || d.items || [] } finally { loading.value = false } }
async function openCreate() { Object.assign(form, { promotion_name: '', real_app_id: '', drama_id: '', chapter_id: '', pixel_id: '', ad_convt_config_id: '', recharge_tpl_id: '', price_strategy_source: 1 }); visible.value = true; const [a, r] = await Promise.all([sinanPromotionsApi.apps(), sinanPromotionsApi.returnRules()]); const raw = a.data?.dist_app_infos || a.data?.items || a.data?.apps || []; apps.value = (Array.isArray(raw) ? raw : []).map((x: any) => ({ ...x, id: x.dist_app_id || x.app_id || x.id, name: x.dist_app_name || x.app_name || x.name })).filter((x: any, i: number, all: any[]) => x.id && all.findIndex(y => String(y.id) === String(x.id)) === i); rules.value = r.data.items || r.data || [] }
async function searchContent(q: string) { if (!q) return; contentLoading.value = true; try { const d = (await sinanPromotionsApi.contentList({ content_type: contentType.value, keyword: q })).data; dramas.value = d.items || d.Dramas || [] } finally { contentLoading.value = false } }
async function loadChapters(id: string) { chapters.value = ((await sinanPromotionsApi.chapters(id)).data.items || []); if (!form.real_app_id) { ElMessage.warning('请先选择推广应用'); return } const [r, p] = await Promise.all([sinanPromotionsApi.rechargeTemplates(String(form.real_app_id)), sinanPromotionsApi.pixels(String(form.real_app_id))]); recharge.value = r.data.recharge_templates || r.data.items || []; pixels.value = p.data.pixel_list || p.data.items || [] }
async function showLink(row: any) { detailVisible.value = true; detail.value = undefined; try { detail.value = (await sinanPromotionsApi.detail(row.promotion_id)).data } catch { ElMessage.error('获取司南推广链接失败') } }
async function copy(value: string) { await navigator.clipboard.writeText(value); ElMessage.success('已复制') }
async function save() { saving.value = true; try { const d = await sinanPromotionsApi.create(form); ElMessage.success('推广链创建成功'); visible.value = false; await load(); if (d.data?.promotion_id) goPublish({ promotion_id: d.data.promotion_id }) } finally { saving.value = false } }
function goPublish(r: any) { router.push({ path: '/dashboard/batch-publish', query: { sinan_promotion_id: r.promotion_id } }) }
watch(contentType, () => { dramas.value = []; chapters.value = []; form.drama_id = ''; form.chapter_id = '' })
onMounted(load)
</script>
<style scoped>.sinan-link-content{border:1px solid #e5e7eb}.sinan-link-row{display:flex;border-bottom:1px solid #e5e7eb;min-height:58px}.sinan-link-row:last-child{border-bottom:0}.sinan-link-label{width:105px;flex:none;padding:16px 12px;background:#f5f7fa;color:#606266;font-weight:600;box-sizing:border-box}.sinan-link-value{flex:1;padding:16px 12px;color:#303133;word-break:break-all;line-height:24px;display:flex;gap:14px;align-items:center}.sinan-link-value span{flex:1}.copy-icon{flex:none;font-size:16px;padding:2px}</style>
