<template><div class="page-container"><div class="page-head"><div><h2 class="page-title">角色与权限</h2><p class="page-subtitle">创建租户内角色模板，统一管理用户权限</p></div><el-button type="primary" @click="openCreate">新建角色</el-button></div><el-card shadow="never"><el-table :data="roles" v-loading="loading" stripe><el-table-column prop="name" label="角色名称"/><el-table-column prop="code" label="编码"/><el-table-column prop="description" label="说明"/><el-table-column label="权限"><template #default="{row}"><el-tag v-for="p in row.permissions" :key="p" size="small" class="tag">{{ p }}</el-tag></template></el-table-column><el-table-column label="操作" width="150"><template #default="{row}"><el-button link type="primary" @click="openEdit(row)">编辑</el-button><el-button v-if="!row.is_system" link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table></el-card><el-dialog v-model="visible" :title="editing ? '编辑角色' : '新建角色'" width="560px"><el-form :model="form" label-width="90px"><el-form-item label="角色名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="角色编码"><el-input v-model="form.code" :disabled="!!editing"/></el-form-item><el-form-item label="说明"><el-input v-model="form.description"/></el-form-item><el-form-item label="权限"><el-checkbox-group v-model="form.permissions"><el-checkbox v-for="p in permissionOptions" :key="p.value" :label="p.value">{{ p.label }}</el-checkbox></el-checkbox-group></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></div></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import { roleApi } from '@/api/admin'
const roles=ref<any[]>([]), loading=ref(false), saving=ref(false), visible=ref(false), editing=ref<any>(null); const form=ref({code:'',name:'',description:'',permissions:[] as string[]})
const permissionOptions=[{value:'meta_asset:manage',label:'Meta 资产管理'},{value:'ad_account:read',label:'查看广告账户'},{value:'ad_account:manage',label:'管理广告账户'},{value:'job:create',label:'创建投放任务'},{value:'job:retry',label:'重试任务'},{value:'insight:read',label:'查看报表'}]
async function load(){loading.value=true;try{roles.value=(await roleApi.list()).data}finally{loading.value=false}}
function openCreate(){editing.value=null;form.value={code:'',name:'',description:'',permissions:[]};visible.value=true} function openEdit(row:any){editing.value=row;form.value={code:row.code,name:row.name,description:row.description||'',permissions:[...(row.permissions||[])]};visible.value=true}
async function save(){saving.value=true;try{if(editing.value)await roleApi.update(editing.value.id,form.value);else await roleApi.create(form.value);visible.value=false;await load();ElMessage.success('已保存')}finally{saving.value=false}}
async function remove(row:any){try{await ElMessageBox.confirm(`确认删除角色「${row.name}」？`,'提示',{type:'warning'});await roleApi.remove(row.id);await load()}catch{}}
onMounted(load)
</script>
<style scoped>.tag{margin:2px 4px 2px 0}</style>
